# Generated by Django 2.2.6 on 2019-11-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_collectingtripimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingtripimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Enter a caption for the image.', max_length=500, null=True),
        ),
    ]
