# Generated by Django 2.2.6 on 2019-11-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20191104_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultfoodimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Enter a caption for the image.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='habitatimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Enter a caption for the image.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hostplantimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Enter a caption for the image.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='immatureimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Enter a caption for the image.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mapimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Enter a caption for the image.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='predatorimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Enter a caption for the image.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='speciesimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Enter a caption for the image.', max_length=500, null=True),
        ),
    ]
