# Generated by Django 2.2.6 on 2019-11-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20191109_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecord',
            name='temperatureF',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Enter the temperature (Fahrenheit) outside at which the specimen was collected.', max_digits=4, null=True, verbose_name='Temperature (°F)'),
        ),
    ]
