# Generated by Django 2.2.6 on 2019-12-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20191212_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='species_page',
        ),
    ]
