# Generated by Django 2.2.10 on 2020-03-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_species_species_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='elevation',
            field=models.CharField(blank=True, help_text='Enter the elevation, in meters.', max_length=15, null=True, verbose_name='Elevation (meters)'),
        ),
    ]
