# Generated by Django 2.2.10 on 2020-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20200320_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectingtrip',
            name='states_collected',
            field=models.ManyToManyField(default='', help_text='Select the states in which specimens were collected on the trip.', to='database.State'),
        ),
    ]
