# Generated by Django 2.2.10 on 2020-03-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_specimenrecord_unidentified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimenrecord',
            name='unidentified',
            field=models.BooleanField(verbose_name='Is the specimen unidentified to species?'),
        ),
    ]
